spring:
  social:
    kakao:
      client_id: f389075420a92087544133981b80ddbb
      redirect: http://localhost:8080/social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
        logout: https://kapi.kakao.com/v2/user/logout


#  url:
#    base: http://localhost:8080

  redis:
    host: localhost
    port: 6379


  datasource:
    url: jdbc:h2:tcp://localhost/~/jpaproject
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 88
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jwt:
    secret: govlepel@$&







#  data:
#    web:
#      pageable:
#        default-page-size: 100
#        max-page-size: 2000
#        one-indexed-parameters: true


logging:
    level:
      org.hibernate.SQL: DEBUG
#      org.hibernate.type: trace